
cc_binary(
    name = "diff_img",
    srcs = ["src/diff_img.cpp"],
    deps = ["@opencv_repo//:opencv_cpp"]
  )



# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
# cc_library(
#   name = "opcv",
#   srcs = [glob("/usr/include/opencv2/**/*.cpp")],
#   hdrs = [glob("/usr/include/opencv2/**/*.hpp")],
#   ##deps = ["header files"],
# )